version: '2'
services:
  redis:
    image: "redis:alpine"
  postgres:
    image: "postgres:9.4"
    environment:
      POSTGRES_DB: thesis
  web:
    build: .
    ports:
     - "80:3000"
    volumes:
     - .:/usr/src/app
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_DB: thesis
      PGUSER: postgres
      PGPASSWORD:
      REDIS_URL: redis://redis
      DATABASE_URL: postgres://postgres
    command: npm run dockerinit
